### ISSUE TITLE
not working - Error

### ISSUE THREAD

**Issue by kclaypool43731** [micjahn/SSMS-Database-Folders#1]
I have placed all the files in the folder but It is not working in SSMS 18 , when I go to the Schema Folders under tools I receive a massage that An error occurred loading this property page.

Any ideas what the issue is?
![SSMS schema Folders Files](https://user-images.githubusercontent.com/115474906/194878084-64956c95-1962-4953-97a8-b0fe1f5efd20.PNG)
![SSMS schema Folders Error](https://user-images.githubusercontent.com/115474906/194878089-934b4100-f6f2-40a0-afd1-9b650fc8598a.PNG)

**Comment by micjahn** [comment]
Did you unblock the unpacked dll files? If not use the right mouse button, select Properties and press the Unblock button at the Properties dialog.

**Comment by kclaypool43731** [comment]
thanks that fixed it.  :)
